// Configuration: .env (secrets + overrides) merged over safe signet defaults.

import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

export const ENV_PATH = path.resolve(process.cwd(), '.env');

// Verified at tip 2026-07-06 (rockshrew 312,009 ≈ bitcoind 312,011): Flex's
// signet Alkanes RPC. Single swap knob SIGNET_RPC_URL; fall back to our local
// index with:  export SIGNET_RPC_URL=http://127.0.0.1:8080
export const DEFAULT_SIGNET_RPC_URL = 'https://signet.l.subfrost.io/v4/jsonrpc';

// Subfrost's hosted RPC requires the x-subfrost-api-key header. Only ever send
// the key to *.subfrost.io — never to a local/other endpoint.
export function isSubfrostHost(url) {
  try {
    return new URL(url).hostname.endsWith('subfrost.io');
  } catch {
    return false;
  }
}

export function parseEnvFile(text) {
  const out = {};
  for (const rawLine of text.split('\n')) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq === -1) continue;
    out[line.slice(0, eq).trim()] = line.slice(eq + 1).trim();
  }
  return out;
}

function loadEnvFile() {
  if (!fs.existsSync(ENV_PATH)) return {};
  const mode = fs.statSync(ENV_PATH).mode & 0o777;
  if ((mode & 0o077) !== 0) {
    console.warn(
      `WARN: ${ENV_PATH} is group/world readable (mode ${mode.toString(8)}); run: chmod 600 .env`,
    );
  }
  return parseEnvFile(fs.readFileSync(ENV_PATH, 'utf8'));
}

function intOpt(v, fallback) {
  if (v === undefined || v === '') return fallback;
  const n = Number(v);
  if (!Number.isFinite(n) || n < 0) throw new Error(`bad numeric config value: ${v}`);
  return n;
}

function boolOpt(v, fallback) {
  if (v === undefined || v === '') return fallback;
  return v === '1' || v.toLowerCase() === 'true';
}

// The Subfrost API key can live in this process's env, in the monolith's own
// .env, or in the shared ~/.subfrost.env. Prefer the first that is set.
function resolveSubfrostApiKey(get) {
  const direct = get('SUBFROST_API_KEY');
  if (direct) return direct;
  try {
    const shared = path.join(os.homedir(), '.subfrost.env');
    if (fs.existsSync(shared)) {
      return parseEnvFile(fs.readFileSync(shared, 'utf8')).SUBFROST_API_KEY ?? null;
    }
  } catch {
    // unreadable ~/.subfrost.env — treat as absent
  }
  return null;
}

export function loadConfig({ env = process.env } = {}) {
  const file = loadEnvFile();
  const get = (k) => env[k] ?? file[k];

  // SIGNET_RPC_URL is the single swap knob (Flex's endpoint ⇄ local index).
  // METASHREW_URL kept as a back-compat alias.
  const metashrewUrl = get('SIGNET_RPC_URL') ?? get('METASHREW_URL') ?? DEFAULT_SIGNET_RPC_URL;
  const subfrostApiKey = resolveSubfrostApiKey(get);

  const cfg = {
    // endpoints
    metashrewUrl,
    // only attached when the read endpoint is a Subfrost host
    subfrostApiKey: isSubfrostHost(metashrewUrl) ? subfrostApiKey : null,
    bitcoindUrl: get('BITCOIND_URL') ?? 'http://127.0.0.1:38332',
    bitcoindUser: get('BITCOIND_USER') ?? 'bitcoinrpc',
    bitcoindPass: get('BITCOIND_PASS') ?? 'bitcoinrpc',
    watchWallet: get('WATCH_WALLET') ?? 'subfrost-monolith-watch',

    // signing key (hex, 32 bytes). Generated by `init`; lives ONLY in .env.
    privKeyHex: get('MONOLITH_PRIVKEY_HEX') ?? null,

    // safety knobs
    minConfirmations: intOpt(get('MIN_CONFIRMATIONS'), 2),
    feeRateSatVb: intOpt(get('FEE_RATE_SAT_VB'), 2),
    maxFeeRateSatVb: intOpt(get('MAX_FEE_RATE_SAT_VB'), 50),
    maxPayoutSats: BigInt(intOpt(get('MAX_PAYOUT_SATS'), 10_000_000)),
    maxSatsPerCycle: BigInt(intOpt(get('MAX_SATS_PER_CYCLE'), 50_000_000)),
    requireSignerMatch: boolOpt(get('REQUIRE_SIGNER_MATCH'), false),
    deepVerify: boolOpt(get('DEEP_VERIFY'), true),
    esploraUrl: get('ESPLORA_URL') ?? 'https://mempool.space/signet/api',

    pollIntervalSec: intOpt(get('POLL_INTERVAL_SEC'), 30),
    dataDir: path.resolve(process.cwd(), get('DATA_DIR') ?? 'data'),

    // frBTC alkane id + opcodes (fixed for signet; here for documentation)
    frbtc: { block: 32n, tx: 0n },
    opGetSigner: 103n,
  };

  if (cfg.privKeyHex !== null && !/^[0-9a-fA-F]{64}$/.test(cfg.privKeyHex)) {
    throw new Error('MONOLITH_PRIVKEY_HEX must be 64 hex chars (32 bytes)');
  }
  return cfg;
}
