// Configuration: .env (secrets + overrides) merged over safe signet defaults.

import fs from 'node:fs';
import path from 'node:path';
// Shared signet RPC endpoint + Subfrost key handling (single swap knob).
import { resolveSignetRpc } from 'alkanes-infra/signet-rpc';

export const ENV_PATH = path.resolve(process.cwd(), '.env');

export function parseEnvFile(text) {
  const out = {};
  for (const rawLine of text.split('\n')) {
    const line = rawLine.trim();
    if (!line || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq === -1) continue;
    out[line.slice(0, eq).trim()] = line.slice(eq + 1).trim();
  }
  return out;
}

function loadEnvFile() {
  if (!fs.existsSync(ENV_PATH)) return {};
  const mode = fs.statSync(ENV_PATH).mode & 0o777;
  if ((mode & 0o077) !== 0) {
    console.warn(
      `WARN: ${ENV_PATH} is group/world readable (mode ${mode.toString(8)}); run: chmod 600 .env`,
    );
  }
  return parseEnvFile(fs.readFileSync(ENV_PATH, 'utf8'));
}

function intOpt(v, fallback) {
  if (v === undefined || v === '') return fallback;
  const n = Number(v);
  if (!Number.isFinite(n) || n < 0) throw new Error(`bad numeric config value: ${v}`);
  return n;
}

function boolOpt(v, fallback) {
  if (v === undefined || v === '') return fallback;
  return v === '1' || v.toLowerCase() === 'true';
}

export function loadConfig({ env = process.env } = {}) {
  const file = loadEnvFile();
  const get = (k) => env[k] ?? file[k];

  // SIGNET_RPC_URL is the single swap knob (Flex's endpoint ⇄ local index);
  // METASHREW_URL kept as a back-compat alias. resolveSignetRpc attaches the
  // Subfrost key ONLY for *.subfrost.io hosts (null otherwise). The `get`
  // getter lets it see the monolith's own .env in addition to process.env and
  // the shared ~/.subfrost.env.
  const { url: metashrewUrl, apiKey: subfrostApiKey } = resolveSignetRpc({
    get,
    aliases: ['METASHREW_URL'],
  });

  const cfg = {
    // endpoints
    metashrewUrl,
    // only attached when the read endpoint is a Subfrost host
    subfrostApiKey,
    bitcoindUrl: get('BITCOIND_URL') ?? 'http://127.0.0.1:38332',
    bitcoindUser: get('BITCOIND_USER') ?? 'bitcoinrpc',
    bitcoindPass: get('BITCOIND_PASS') ?? 'bitcoinrpc',
    watchWallet: get('WATCH_WALLET') ?? 'subfrost-monolith-watch',

    // signing key (hex, 32 bytes). Generated by `init`; lives ONLY in .env.
    privKeyHex: get('MONOLITH_PRIVKEY_HEX') ?? null,

    // safety knobs
    minConfirmations: intOpt(get('MIN_CONFIRMATIONS'), 2),
    feeRateSatVb: intOpt(get('FEE_RATE_SAT_VB'), 2),
    maxFeeRateSatVb: intOpt(get('MAX_FEE_RATE_SAT_VB'), 50),
    maxPayoutSats: BigInt(intOpt(get('MAX_PAYOUT_SATS'), 10_000_000)),
    maxSatsPerCycle: BigInt(intOpt(get('MAX_SATS_PER_CYCLE'), 50_000_000)),
    requireSignerMatch: boolOpt(get('REQUIRE_SIGNER_MATCH'), false),
    deepVerify: boolOpt(get('DEEP_VERIFY'), true),
    esploraUrl: get('ESPLORA_URL') ?? 'https://mempool.space/signet/api',

    pollIntervalSec: intOpt(get('POLL_INTERVAL_SEC'), 30),
    dataDir: path.resolve(process.cwd(), get('DATA_DIR') ?? 'data'),

    // frBTC alkane id + opcodes (fixed for signet; here for documentation)
    frbtc: { block: 32n, tx: 0n },
    opGetSigner: 103n,
  };

  if (cfg.privKeyHex !== null && !/^[0-9a-fA-F]{64}$/.test(cfg.privKeyHex)) {
    throw new Error('MONOLITH_PRIVKEY_HEX must be 64 hex chars (32 bytes)');
  }
  return cfg;
}
